# Makefile
#
# 2015/1/28
# Waheed Brown
#
# Blackjack

all:
	g++ blackjack.cpp game.cpp cards.cpp -o blackjack
debug:
	g++ -g blackjack.cpp game.cpp cards.cpp -o blackjack
clean:
	rm -rf *o
	rm -rf *#
	rm -rf *~
	rm -rf *dSYM
	rm -rf blackjack

