# Makefile
#
# 2015/9/2
# Waheed Brown
#
# OLG - Overlapping Generations Game

all:
	g++ olg.cpp game.cpp player.cpp action.cpp bank.cpp -std=c++0x -o olg
debug:
	g++ -g olg.cpp game.cpp player.cpp action.cpp bank.cpp -std=c++0x -o olg
clean:
	rm -rf *o
	rm -rf *#
	rm -rf *~
	rm -rf *dSYM
	rm -rf olg

